FROM golang:1.25.3

WORKDIR /
COPY apis /apis
COPY contribs /contribs
COPY mongo /mongo

WORKDIR /contribs
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o bin
RUN export PATH=$PATH:/usr/local/go/bin

CMD ["./bin"]
