FROM golang:1.22

WORKDIR /
COPY apis /apis
COPY mongo /mongo

WORKDIR /apis
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o apis_go
RUN export PATH=$PATH:/usr/local/go/bin

CMD ["./apis_go"]
