FROM python:3.9-slim

RUN pip install pipreqs

WORKDIR /
COPY contribs /contribs
COPY mongo /mongo

WORKDIR /mongo
RUN pipreqs .
RUN pip install -r requirements.txt

WORKDIR /contribs
COPY *.py /
RUN pipreqs .
RUN pip install -r requirements.txt

CMD ["python", "__main__.py"]
